services:
  premier-league-db:
    image: mysql:8.0
    container_name: premier-league-db
    hostname: premier-league-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

    networks:
      - premier-league-network

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  premier-league-be:
    build:
      dockerfile: Dockerfile
    container_name: premier-league-be
    restart: unless-stopped
    environment:
      - APP_NAME
      - APP_ENV
      - APP_KEY
      - APP_DEBUG
      - APP_URL
      - LOG_CHANNEL
      - LOG_DEPRECATIONS_CHANNEL
      - LOG_LEVEL
      - DB_CONNECTION
      - DB_HOST
      - DB_PORT
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
      - BROADCAST_DRIVER
      - CACHE_DRIVER
      - FILESYSTEM_DISK
      - QUEUE_CONNECTION
      - SESSION_DRIVER
      - SESSION_LIFETIME
      - MEMCACHED_HOST
      - REDIS_HOST
      - REDIS_PASSWORD
      - REDIS_PORT
      - MAIL_MAILER
      - MAIL_HOST
      - MAIL_PORT
      - MAIL_USERNAME
      - MAIL_PASSWORD
      - MAIL_ENCRYPTION
      - MAIL_FROM_ADDRESS
      - MAIL_FROM_NAME
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - AWS_BUCKET
      - AWS_USE_PATH_STYLE_ENDPOINT
      - PUSHER_APP_ID
      - PUSHER_APP_KEY
      - PUSHER_APP_SECRET
      - PUSHER_HOST
      - PUSHER_PORT
      - PUSHER_SCHEME
      - PUSHER_APP_CLUSTER
      - VITE_APP_NAME
      - VITE_PUSHER_APP_KEY
      - VITE_PUSHER_HOST
      - VITE_PUSHER_PORT
      - VITE_PUSHER_SCHEME
      - VITE_PUSHER_APP_CLUSTER

    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    depends_on:
      premier-league-db:
        condition: service_healthy
    networks:
      - premier-league-network
    command: php artisan serve --host=0.0.0.0 --port=8000

  premier-league-fe:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: premier-league-fe
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - premier-league-be
    networks:
      - premier-league-network

networks:
  premier-league-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
